### ISSUE TITLE
gulp-flowtype conflicts with gulpfile.babel.js ""only one instance of babel/polyfill is allowed"

### ISSUE THREAD

**Issue by Bnaya** [charliedowler/gulp-flowtype#39]
When using es6/babel gulp file and importing gulp-flowtype
```
// gulpfile.babel.js
import gulpFlowtype from 'gulp-flowtype';
// Or
var gulpFlowtype = require('gulp-flowtype');
```

it throws the following error:
```
/Users/***/node_modules/gulp-flowtype/node_modules/babel/node_modules/babel-core/lib/polyfill.js:8
  throw new Error("only one instance of babel/polyfill is allowed");
  ^

Error: only one instance of babel/polyfill is allowed
    at Object.<anonymous> (/Users/***/node_modules/gulp-flowtype/node_modules/babel/node_modules/babel-core/lib/polyfill.js:8:9)
    at Module._compile (module.js:398:26)
    at Module._extensions..js (module.js:405:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/***/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/***/node_modules/gulp-flowtype/node_modules/babel/node_modules/babel-core/polyfill.js:1:80)
    at Module._compile (module.js:398:26)
```

**Comment by jphilipstevens** [comment]
I was trying the same this morning and got the same error. Any updates, or at least a workaround?

**Comment by Alexandre-Herve** [comment]
Same here

**Comment by jphilipstevens** [comment]
I ended up having to update my project to Babel 6. Now I can use this task

**Comment by charliedowler** [comment]
Releasing a new version soon, is this still affecting anyone?

Cheers
