### ISSUE TITLE
Installation of flow-bin seems to fail in windows

### ISSUE THREAD

**Issue by HeavyStorm** [charliedowler/gulp-flowtype#45]
It seems that the post install event of flow-bin isn't being ran in Windows. Gulp fails with:

```
[20:06:02] Using gulpfile c:\Users\[redacted]\gulpfile.js
[20:06:02] Starting 'typecheck'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn c:\Users\[redacted]\node_modules\gulp-flowtype\node_modules\flow-bin\vendor\flow.exe ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I was able to circumvent the issue by cding into gulp-flowtype and installing `flow-bin`.

**Comment by charliedowler** [comment]
Hi,

Closing the issue as I don't believe this is an issue with gulp-flowtype.

Cheers

**Comment by tyger** [comment]
In the latest version `flow-bin` is only required as `devDependency`. In production mode `flow-bin` should be installed as `peerDependency` by user manually.

@charliedowler I can check the latest version on Windows, but before it's better to merge my pull request which is fixing current issues with tests in the project.
